/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/Toast/Toast`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/Toast/Toast.styles`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/Toast/Toast.types`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/Toast/index`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/ToastProvider/ToastProvider`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/ToastProvider/ToastProvider.styles`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/ToastProvider/ToastProviter.types`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/ToastProvider/index`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/formulario` | `/formulario`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/historico` | `/historico`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/Toast/Toast`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/Toast/Toast.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/Toast/Toast.types`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/Toast/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/ToastProvider/ToastProvider`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/ToastProvider/ToastProvider.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/ToastProvider/ToastProviter.types`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/ToastProvider/index`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/formulario` | `/formulario`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/historico` | `/historico`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../components/ui/Toast/Toast${`?${string}` | `#${string}` | ''}` | `/../components/ui/Toast/Toast.styles${`?${string}` | `#${string}` | ''}` | `/../components/ui/Toast/Toast.types${`?${string}` | `#${string}` | ''}` | `/../components/ui/Toast/index${`?${string}` | `#${string}` | ''}` | `/../components/ui/ToastProvider/ToastProvider${`?${string}` | `#${string}` | ''}` | `/../components/ui/ToastProvider/ToastProvider.styles${`?${string}` | `#${string}` | ''}` | `/../components/ui/ToastProvider/ToastProviter.types${`?${string}` | `#${string}` | ''}` | `/../components/ui/ToastProvider/index${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/formulario${`?${string}` | `#${string}` | ''}` | `/formulario${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/historico${`?${string}` | `#${string}` | ''}` | `/historico${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/Toast/Toast`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/Toast/Toast.styles`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/Toast/Toast.types`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/Toast/index`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/ToastProvider/ToastProvider`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/ToastProvider/ToastProvider.styles`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/ToastProvider/ToastProviter.types`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/ToastProvider/index`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/formulario` | `/formulario`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/historico` | `/historico`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
    }
  }
}
