/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../components/ui/Header/Header`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/Header/index`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/Header/Header.styles`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/Header/Header.types`; params?: Router.UnknownInputParams; } | { pathname: `/../components/layout/styles`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/formulario` | `/formulario`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/historico` | `/historico`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../components/ui/Header/Header`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/Header/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/Header/Header.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/Header/Header.types`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/layout/styles`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/formulario` | `/formulario`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/historico` | `/historico`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/../components/ui/Header/Header${`?${string}` | `#${string}` | ''}` | `/../components/ui/Header/index${`?${string}` | `#${string}` | ''}` | `/../components/ui/Header/Header.styles${`?${string}` | `#${string}` | ''}` | `/../components/ui/Header/Header.types${`?${string}` | `#${string}` | ''}` | `/../components/layout/styles${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/formulario${`?${string}` | `#${string}` | ''}` | `/formulario${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/historico${`?${string}` | `#${string}` | ''}` | `/historico${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../components/ui/Header/Header`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/Header/index`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/Header/Header.styles`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/Header/Header.types`; params?: Router.UnknownInputParams; } | { pathname: `/../components/layout/styles`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/formulario` | `/formulario`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/historico` | `/historico`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
    }
  }
}
